-- ============================================================
-- Affirmation library seed — 350 lines (25 × 14 categories)
-- Style: 3–12 words, concise, reflective, slightly philosophical.
-- Idempotent: unique (category, text) + on conflict do nothing.
-- Apply: supabase db execute -f supabase/seed/affirmation_library.sql
-- ============================================================

insert into public.affirmation_library
  (text, category, tones, energy, difficulty, tags, addresses, word_count)
values
-- ── Confidence ──────────────────────────────────────────────────────────────────
($a$I trust my own voice.$a$, 'confidence', '{gentle,practical}', 3, 'beginner', '{self-trust,self-worth}', '{build-confidence,self-doubt}', 5),
($a$I take up space.$a$, 'confidence', '{motivational}', 4, 'beginner', '{self-worth}', '{build-confidence}', 4),
($a$I have done hard things before.$a$, 'confidence', '{practical}', 3, 'beginner', '{self-trust,courage}', '{self-doubt,fear-of-failure}', 6),
($a$I am allowed to be seen.$a$, 'confidence', '{gentle}', 3, 'beginner', '{self-worth}', '{build-confidence}', 6),
($a$My doubts are not facts.$a$, 'confidence', '{practical}', 3, 'intermediate', '{self-trust}', '{self-doubt,negative-self-talk}', 5),
($a$I act before the fear fades.$a$, 'confidence', '{motivational}', 4, 'intermediate', '{courage,action}', '{fear-of-failure}', 6),
($a$I stand on my own ground.$a$, 'confidence', '{practical}', 3, 'intermediate', '{self-trust}', '{build-confidence}', 6),
($a$Certainty is built, not waited for.$a$, 'confidence', '{practical}', 3, 'advanced', '{self-trust}', '{}', 6),
($a$Worth is not earned; it is.$a$, 'confidence', '{spiritual}', 2, 'advanced', '{self-worth}', '{comparison}', 6),
($a$Quiet confidence needs no audience.$a$, 'confidence', '{spiritual}', 2, 'advanced', '{self-worth}', '{comparison}', 5),
($a$I speak even when my voice shakes.$a$, 'confidence', '{gentle}', 3, 'intermediate', '{courage}', '{self-doubt}', 7),
($a$I am not for everyone, and that's fine.$a$, 'confidence', '{humorous,gentle}', 3, 'intermediate', '{self-acceptance}', '{comparison}', 8),
($a$I let myself be a beginner in public.$a$, 'confidence', '{gentle}', 3, 'intermediate', '{growth,courage}', '{fear-of-failure}', 8),
($a$My presence is enough to bring.$a$, 'confidence', '{gentle}', 3, 'beginner', '{self-worth}', '{}', 6),
($a$I keep promises to myself.$a$, 'confidence', '{practical}', 3, 'beginner', '{self-trust}', '{}', 5),
($a$Approval is pleasant, not necessary.$a$, 'confidence', '{practical}', 3, 'advanced', '{self-worth}', '{comparison}', 5),
($a$I outgrow the need to prove.$a$, 'confidence', '{spiritual}', 2, 'advanced', '{self-worth}', '{comparison}', 6),
($a$I can be unsure and still decide.$a$, 'confidence', '{practical}', 3, 'intermediate', '{courage}', '{self-doubt}', 7),
($a$I am the authority on me.$a$, 'confidence', '{motivational}', 4, 'beginner', '{self-trust}', '{}', 6),
($a$Confidence is just familiarity with fear.$a$, 'confidence', '{practical}', 3, 'advanced', '{courage}', '{fear-of-failure}', 6),
($a$I do not audition for my own life.$a$, 'confidence', '{practical}', 3, 'advanced', '{self-worth}', '{comparison}', 8),
($a$I trust the version of me that shows up.$a$, 'confidence', '{gentle}', 3, 'intermediate', '{self-trust}', '{}', 9),
($a$I have nothing to defend.$a$, 'confidence', '{spiritual}', 2, 'advanced', '{self-acceptance}', '{}', 5),
($a$I belong in the room.$a$, 'confidence', '{motivational}', 4, 'beginner', '{self-worth,belonging}', '{comparison}', 5),
($a$I answer to my own standards.$a$, 'confidence', '{practical}', 3, 'intermediate', '{self-trust}', '{comparison}', 6),

-- ── Career ──────────────────────────────────────────────────────────────────────
($a$My skills are still arriving.$a$, 'career', '{gentle}', 3, 'beginner', '{growth}', '{career-growth}', 5),
($a$My work speaks for itself.$a$, 'career', '{practical}', 3, 'beginner', '{self-worth}', '{}', 5),
($a$I am allowed to be a beginner.$a$, 'career', '{gentle}', 2, 'beginner', '{growth}', '{fear-of-failure}', 6),
($a$I build slowly and on purpose.$a$, 'career', '{practical}', 3, 'intermediate', '{growth}', '{career-growth}', 6),
($a$I lead before I feel ready.$a$, 'career', '{motivational}', 4, 'intermediate', '{courage}', '{career-growth}', 6),
($a$My effort compounds quietly.$a$, 'career', '{practical}', 3, 'intermediate', '{momentum}', '{}', 4),
($a$Skill follows showing up.$a$, 'career', '{practical}', 3, 'intermediate', '{growth,mastery}', '{}', 4),
($a$Mastery is patience repeated.$a$, 'career', '{spiritual}', 2, 'advanced', '{mastery}', '{}', 4),
($a$Ambition and ease can coexist.$a$, 'career', '{practical}', 3, 'advanced', '{balance}', '{work-life-balance}', 5),
($a$I measure depth, not speed.$a$, 'career', '{practical}', 3, 'advanced', '{mastery}', '{comparison}', 5),
($a$I am paid to solve, not to please.$a$, 'career', '{practical}', 3, 'advanced', '{self-worth}', '{}', 8),
($a$I let my work be unfinished.$a$, 'career', '{gentle}', 2, 'intermediate', '{letting-go}', '{}', 6),
($a$I learn in the open.$a$, 'career', '{practical}', 3, 'beginner', '{growth,curiosity}', '{}', 5),
($a$Reputation is a slow harvest.$a$, 'career', '{spiritual}', 2, 'advanced', '{growth}', '{}', 5),
($a$I do the boring parts well.$a$, 'career', '{practical}', 3, 'beginner', '{action}', '{procrastination}', 6),
($a$I am more than my last result.$a$, 'career', '{gentle}', 2, 'beginner', '{self-worth}', '{fear-of-failure}', 7),
($a$Careers are built in quiet hours.$a$, 'career', '{practical}', 3, 'advanced', '{momentum}', '{}', 6),
($a$I ask for what my work is worth.$a$, 'career', '{motivational}', 4, 'intermediate', '{self-worth}', '{career-growth}', 8),
($a$I choose problems worth having.$a$, 'career', '{practical}', 3, 'advanced', '{direction}', '{}', 5),
($a$I grow toward, not away.$a$, 'career', '{spiritual}', 2, 'intermediate', '{growth}', '{}', 5),
($a$Effort I can control; outcomes I cannot.$a$, 'career', '{practical}', 3, 'advanced', '{letting-go}', '{}', 7),
($a$I am still drafting my path.$a$, 'career', '{gentle}', 2, 'beginner', '{direction,growth}', '{}', 6),
($a$Small competence stacks into range.$a$, 'career', '{practical}', 3, 'intermediate', '{mastery}', '{}', 5),
($a$I work like it matters, lightly.$a$, 'career', '{practical}', 3, 'advanced', '{balance}', '{work-life-balance}', 6),
($a$I make room to be wrong.$a$, 'career', '{gentle}', 2, 'beginner', '{growth,courage}', '{fear-of-failure}', 6),

-- ── Anxiety & Stress ────────────────────────────────────────────────────────────
($a$I release what I cannot control.$a$, 'anxiety_stress', '{gentle}', 2, 'beginner', '{letting-go,calm}', '{stress-overwhelm,fear-of-failure}', 6),
($a$This feeling will pass.$a$, 'anxiety_stress', '{gentle}', 1, 'beginner', '{calm}', '{stress-overwhelm}', 4),
($a$I return to my breath.$a$, 'anxiety_stress', '{gentle}', 1, 'beginner', '{grounding,presence}', '{stress-overwhelm}', 5),
($a$I am safe in this breath.$a$, 'anxiety_stress', '{gentle}', 1, 'beginner', '{grounding,calm}', '{stress-overwhelm}', 6),
($a$Peace begins with acceptance.$a$, 'anxiety_stress', '{gentle}', 2, 'intermediate', '{acceptance,calm}', '{stress-overwhelm}', 4),
($a$I meet this moment as it is.$a$, 'anxiety_stress', '{spiritual}', 2, 'intermediate', '{presence,acceptance}', '{stress-overwhelm}', 7),
($a$Stillness is a place I can reach.$a$, 'anxiety_stress', '{spiritual}', 2, 'intermediate', '{calm,presence}', '{stress-overwhelm}', 7),
($a$Most of my fears never arrive.$a$, 'anxiety_stress', '{practical}', 3, 'advanced', '{letting-go}', '{stress-overwhelm,fear-of-failure}', 6),
($a$Not every thought deserves my attention.$a$, 'anxiety_stress', '{practical}', 3, 'advanced', '{letting-go}', '{negative-self-talk}', 6),
($a$Calm is a practice, not a mood.$a$, 'anxiety_stress', '{practical}', 3, 'advanced', '{calm}', '{}', 6),
($a$The wave rises and the wave falls.$a$, 'anxiety_stress', '{spiritual}', 2, 'intermediate', '{impermanence,calm}', '{stress-overwhelm}', 8),
($a$I unclench what I have been gripping.$a$, 'anxiety_stress', '{gentle}', 2, 'intermediate', '{letting-go}', '{stress-overwhelm}', 7),
($a$I can be anxious and still functional.$a$, 'anxiety_stress', '{practical}', 3, 'intermediate', '{acceptance}', '{stress-overwhelm}', 7),
($a$Soon this will be a memory.$a$, 'anxiety_stress', '{gentle}', 2, 'beginner', '{impermanence}', '{stress-overwhelm}', 6),
($a$I let my shoulders drop.$a$, 'anxiety_stress', '{gentle}', 1, 'beginner', '{grounding}', '{stress-overwhelm}', 5),
($a$Panic is loud, not true.$a$, 'anxiety_stress', '{practical}', 3, 'advanced', '{calm}', '{stress-overwhelm}', 5),
($a$I do the next small thing.$a$, 'anxiety_stress', '{practical}', 3, 'beginner', '{action,grounding}', '{stress-overwhelm}', 6),
($a$My nervous system can learn calm.$a$, 'anxiety_stress', '{practical}', 3, 'advanced', '{calm}', '{stress-overwhelm}', 6),
($a$I am not the storm, only the sky.$a$, 'anxiety_stress', '{spiritual}', 2, 'advanced', '{presence,calm}', '{stress-overwhelm}', 9),
($a$Slow breath, slower mind.$a$, 'anxiety_stress', '{gentle}', 1, 'beginner', '{grounding,calm}', '{stress-overwhelm}', 4),
($a$I trade what-ifs for what-is.$a$, 'anxiety_stress', '{practical}', 3, 'advanced', '{presence,letting-go}', '{stress-overwhelm}', 5),
($a$Pressure is not the same as danger.$a$, 'anxiety_stress', '{practical}', 3, 'advanced', '{calm}', '{stress-overwhelm}', 7),
($a$I give worry a smaller room.$a$, 'anxiety_stress', '{gentle}', 2, 'intermediate', '{letting-go}', '{stress-overwhelm}', 6),
($a$I have time for one breath.$a$, 'anxiety_stress', '{gentle}', 1, 'beginner', '{grounding,presence}', '{stress-overwhelm}', 6),
($a$Ease is allowed, even now.$a$, 'anxiety_stress', '{gentle}', 2, 'intermediate', '{calm,acceptance}', '{stress-overwhelm}', 5),

-- ── Self-Love ───────────────────────────────────────────────────────────────────
($a$I am kind to myself today.$a$, 'self_love', '{gentle}', 2, 'beginner', '{self-compassion}', '{negative-self-talk}', 6),
($a$I am on my own side.$a$, 'self_love', '{gentle}', 2, 'beginner', '{self-compassion}', '{negative-self-talk}', 6),
($a$I speak to myself gently.$a$, 'self_love', '{gentle}', 2, 'beginner', '{self-compassion}', '{negative-self-talk}', 5),
($a$I deserve my own care.$a$, 'self_love', '{gentle}', 2, 'beginner', '{self-worth}', '{}', 5),
($a$I am not my harshest thought.$a$, 'self_love', '{practical}', 3, 'intermediate', '{self-acceptance}', '{negative-self-talk}', 6),
($a$I am a work in progress, and whole.$a$, 'self_love', '{gentle}', 2, 'intermediate', '{self-acceptance}', '{comparison}', 9),
($a$I forgive my earlier self.$a$, 'self_love', '{gentle}', 2, 'intermediate', '{healing,self-compassion}', '{grief-loss}', 5),
($a$Self-respect is a quiet loyalty.$a$, 'self_love', '{spiritual}', 2, 'advanced', '{self-worth}', '{}', 5),
($a$I meet myself without conditions.$a$, 'self_love', '{spiritual}', 2, 'advanced', '{self-acceptance}', '{}', 5),
($a$I belong to myself first.$a$, 'self_love', '{practical}', 3, 'advanced', '{self-worth,boundaries}', '{}', 5),
($a$I am not behind.$a$, 'self_love', '{gentle}', 2, 'beginner', '{self-acceptance}', '{comparison}', 4),
($a$I outgrew who hurt me.$a$, 'self_love', '{practical}', 3, 'intermediate', '{healing}', '{grief-loss}', 5),
($a$My worth is not up for debate.$a$, 'self_love', '{motivational}', 4, 'intermediate', '{self-worth}', '{comparison}', 7),
($a$I keep myself good company.$a$, 'self_love', '{gentle}', 2, 'beginner', '{self-compassion}', '{loneliness}', 5),
($a$I am allowed to disappoint others.$a$, 'self_love', '{practical}', 3, 'advanced', '{boundaries}', '{}', 6),
($a$I rest without earning it.$a$, 'self_love', '{gentle}', 2, 'intermediate', '{self-compassion,rest}', '{}', 5),
($a$I am my longest relationship.$a$, 'self_love', '{spiritual}', 2, 'advanced', '{self-worth}', '{loneliness}', 5),
($a$I stopped auditing my own worth.$a$, 'self_love', '{practical}', 3, 'advanced', '{self-acceptance}', '{comparison}', 6),
($a$I treat my name kindly.$a$, 'self_love', '{gentle}', 2, 'intermediate', '{self-compassion}', '{negative-self-talk}', 5),
($a$I am softer with myself now.$a$, 'self_love', '{gentle}', 2, 'beginner', '{self-compassion}', '{negative-self-talk}', 6),
($a$I am not a rough draft to fix.$a$, 'self_love', '{practical}', 3, 'advanced', '{self-acceptance}', '{negative-self-talk}', 8),
($a$I let myself be liked.$a$, 'self_love', '{gentle}', 2, 'intermediate', '{self-acceptance}', '{}', 5),
($a$I take my own side in the argument.$a$, 'self_love', '{practical}', 3, 'intermediate', '{self-compassion}', '{negative-self-talk}', 8),
($a$Self-worth needs no receipts.$a$, 'self_love', '{practical}', 3, 'advanced', '{self-worth}', '{comparison}', 4),
($a$I am good company for now.$a$, 'self_love', '{gentle}', 2, 'beginner', '{self-compassion}', '{loneliness}', 6),

-- ── Relationships ───────────────────────────────────────────────────────────────
($a$I give and receive love freely.$a$, 'relationships', '{gentle}', 3, 'beginner', '{connection}', '{loneliness}', 6),
($a$My boundaries protect my peace.$a$, 'relationships', '{practical}', 3, 'beginner', '{boundaries}', '{work-life-balance}', 5),
($a$I belong where I am valued.$a$, 'relationships', '{gentle}', 3, 'beginner', '{belonging}', '{loneliness}', 6),
($a$Connection begins with honesty.$a$, 'relationships', '{practical}', 3, 'intermediate', '{connection}', '{}', 4),
($a$I can love and still let go.$a$, 'relationships', '{gentle}', 2, 'intermediate', '{boundaries,letting-go}', '{grief-loss}', 7),
($a$I do not shrink to be loved.$a$, 'relationships', '{motivational}', 4, 'intermediate', '{self-worth,boundaries}', '{}', 7),
($a$I let people meet the real me.$a$, 'relationships', '{gentle}', 3, 'intermediate', '{connection}', '{loneliness}', 7),
($a$Closeness asks for courage.$a$, 'relationships', '{spiritual}', 2, 'advanced', '{courage,connection}', '{}', 4),
($a$Love is shown, not announced.$a$, 'relationships', '{practical}', 3, 'advanced', '{connection}', '{}', 5),
($a$Distance can be its own kindness.$a$, 'relationships', '{spiritual}', 2, 'advanced', '{boundaries}', '{}', 6),
($a$I let love be slow.$a$, 'relationships', '{gentle}', 2, 'intermediate', '{connection}', '{}', 5),
($a$I say the hard, kind thing.$a$, 'relationships', '{practical}', 3, 'intermediate', '{boundaries,connection}', '{}', 6),
($a$I do not chase what avoids me.$a$, 'relationships', '{practical}', 3, 'intermediate', '{boundaries}', '{}', 7),
($a$I am chosen and I choose.$a$, 'relationships', '{gentle}', 3, 'beginner', '{belonging}', '{}', 6),
($a$Closeness survives honesty.$a$, 'relationships', '{spiritual}', 2, 'advanced', '{connection}', '{}', 3),
($a$I keep my own name in love.$a$, 'relationships', '{practical}', 3, 'advanced', '{boundaries}', '{}', 7),
($a$I forgive without forgetting the lesson.$a$, 'relationships', '{practical}', 3, 'intermediate', '{healing}', '{grief-loss}', 6),
($a$I let some bridges rest.$a$, 'relationships', '{gentle}', 2, 'advanced', '{boundaries,letting-go}', '{}', 5),
($a$I show up before I am asked.$a$, 'relationships', '{gentle}', 3, 'beginner', '{connection}', '{}', 7),
($a$Good love feels like ease.$a$, 'relationships', '{gentle}', 2, 'intermediate', '{connection}', '{}', 5),
($a$I am not responsible for their weather.$a$, 'relationships', '{practical}', 3, 'advanced', '{boundaries}', '{}', 7),
($a$I let people be fully themselves.$a$, 'relationships', '{gentle}', 3, 'intermediate', '{connection,boundaries}', '{}', 6),
($a$I trust what is steady over what is loud.$a$, 'relationships', '{spiritual}', 2, 'advanced', '{connection}', '{}', 9),
($a$I make room, not myself smaller.$a$, 'relationships', '{motivational}', 4, 'intermediate', '{boundaries,self-worth}', '{}', 6),
($a$Being known is worth the risk.$a$, 'relationships', '{gentle}', 3, 'intermediate', '{connection,courage}', '{loneliness}', 6),

-- ── Productivity ────────────────────────────────────────────────────────────────
($a$I begin before I feel ready.$a$, 'productivity', '{motivational}', 4, 'beginner', '{action}', '{procrastination}', 6),
($a$One thing at a time.$a$, 'productivity', '{practical}', 3, 'beginner', '{focus}', '{stress-overwhelm}', 5),
($a$Small steps still move me.$a$, 'productivity', '{gentle}', 3, 'beginner', '{momentum}', '{procrastination}', 5),
($a$Clarity follows action.$a$, 'productivity', '{practical}', 3, 'intermediate', '{action}', '{procrastination}', 3),
($a$Done is its own momentum.$a$, 'productivity', '{practical}', 3, 'intermediate', '{momentum}', '{procrastination}', 5),
($a$I protect my attention.$a$, 'productivity', '{practical}', 3, 'intermediate', '{focus}', '{}', 4),
($a$Rest is part of the work.$a$, 'productivity', '{gentle}', 2, 'intermediate', '{rest,balance}', '{work-life-balance}', 6),
($a$Focus is a kind of devotion.$a$, 'productivity', '{spiritual}', 2, 'advanced', '{focus}', '{}', 6),
($a$Urgency is not importance.$a$, 'productivity', '{practical}', 3, 'advanced', '{focus}', '{}', 4),
($a$Starting is the hardest mile.$a$, 'productivity', '{practical}', 3, 'advanced', '{action}', '{procrastination}', 5),
($a$Motion is not the same as progress.$a$, 'productivity', '{practical}', 3, 'advanced', '{focus}', '{}', 7),
($a$I finish more than I start.$a$, 'productivity', '{practical}', 3, 'intermediate', '{momentum}', '{procrastination}', 6),
($a$I let good enough be done.$a$, 'productivity', '{gentle}', 2, 'intermediate', '{letting-go}', '{procrastination}', 6),
($a$I work with my energy, not against it.$a$, 'productivity', '{practical}', 3, 'intermediate', '{balance,energy}', '{low-energy}', 8),
($a$Busy is not the goal.$a$, 'productivity', '{practical}', 3, 'advanced', '{focus}', '{}', 5),
($a$I clear one thing, then the next.$a$, 'productivity', '{practical}', 3, 'beginner', '{action}', '{stress-overwhelm}', 7),
($a$I guard the first hour.$a$, 'productivity', '{practical}', 3, 'intermediate', '{focus}', '{}', 5),
($a$I stop before I am empty.$a$, 'productivity', '{gentle}', 2, 'intermediate', '{rest,balance}', '{low-energy}', 6),
($a$Momentum likes a small beginning.$a$, 'productivity', '{practical}', 3, 'intermediate', '{momentum}', '{procrastination}', 5),
($a$I do less, better.$a$, 'productivity', '{practical}', 3, 'beginner', '{focus}', '{}', 4),
($a$Deep work needs a quiet door.$a$, 'productivity', '{practical}', 3, 'advanced', '{focus}', '{}', 6),
($a$One window, one task.$a$, 'productivity', '{practical}', 3, 'beginner', '{focus}', '{}', 4),
($a$I let the list wait sometimes.$a$, 'productivity', '{gentle}', 2, 'beginner', '{balance,letting-go}', '{work-life-balance}', 6),
($a$Effort is mine; speed varies.$a$, 'productivity', '{practical}', 3, 'intermediate', '{letting-go}', '{comparison}', 5),
($a$I begin where I am.$a$, 'productivity', '{gentle}', 2, 'beginner', '{action}', '{procrastination}', 5),

-- ── Gratitude ───────────────────────────────────────────────────────────────────
($a$I notice the good already here.$a$, 'gratitude', '{gentle}', 2, 'beginner', '{appreciation,presence}', '{}', 6),
($a$Today gave me something.$a$, 'gratitude', '{gentle}', 2, 'beginner', '{appreciation}', '{}', 4),
($a$I let enough be enough.$a$, 'gratitude', '{spiritual}', 2, 'beginner', '{appreciation}', '{}', 5),
($a$Enough is its own abundance.$a$, 'gratitude', '{spiritual}', 2, 'intermediate', '{appreciation,abundance}', '{}', 5),
($a$I hold this moment lightly.$a$, 'gratitude', '{spiritual}', 2, 'intermediate', '{presence}', '{}', 5),
($a$I have more than I name.$a$, 'gratitude', '{gentle}', 2, 'intermediate', '{abundance}', '{}', 6),
($a$I receive without rushing past.$a$, 'gratitude', '{gentle}', 2, 'intermediate', '{presence}', '{}', 5),
($a$Attention is a form of thanks.$a$, 'gratitude', '{spiritual}', 2, 'advanced', '{appreciation,presence}', '{}', 6),
($a$Ordinary days are not empty.$a$, 'gratitude', '{spiritual}', 2, 'advanced', '{appreciation}', '{}', 5),
($a$Gratitude widens the small.$a$, 'gratitude', '{spiritual}', 2, 'advanced', '{appreciation}', '{}', 4),
($a$I let the small things count.$a$, 'gratitude', '{gentle}', 2, 'beginner', '{appreciation}', '{}', 6),
($a$I keep what I already have.$a$, 'gratitude', '{practical}', 3, 'beginner', '{appreciation}', '{}', 6),
($a$Noticing is its own wealth.$a$, 'gratitude', '{spiritual}', 2, 'advanced', '{appreciation,abundance}', '{}', 5),
($a$I thank the day before it ends.$a$, 'gratitude', '{gentle}', 2, 'beginner', '{appreciation}', '{}', 7),
($a$Enough was here all along.$a$, 'gratitude', '{spiritual}', 2, 'intermediate', '{appreciation,abundance}', '{}', 5),
($a$I collect ordinary good.$a$, 'gratitude', '{gentle}', 2, 'intermediate', '{appreciation}', '{}', 4),
($a$I am rich in things I forget.$a$, 'gratitude', '{spiritual}', 2, 'advanced', '{abundance}', '{}', 7),
($a$I slow down to see it.$a$, 'gratitude', '{gentle}', 2, 'intermediate', '{presence}', '{}', 6),
($a$Gladness hides in plain sight.$a$, 'gratitude', '{spiritual}', 2, 'advanced', '{appreciation}', '{}', 5),
($a$I owe this moment my attention.$a$, 'gratitude', '{spiritual}', 2, 'intermediate', '{presence}', '{}', 6),
($a$I count what stays, not what is missing.$a$, 'gratitude', '{practical}', 3, 'advanced', '{appreciation}', '{comparison}', 8),
($a$A full breath is already a gift.$a$, 'gratitude', '{gentle}', 2, 'intermediate', '{presence,appreciation}', '{}', 7),
($a$I let myself be easily pleased.$a$, 'gratitude', '{gentle}', 2, 'beginner', '{appreciation}', '{}', 6),
($a$Plenty is a way of looking.$a$, 'gratitude', '{spiritual}', 2, 'advanced', '{abundance}', '{}', 6),
($a$I am glad without a reason.$a$, 'gratitude', '{gentle}', 2, 'intermediate', '{appreciation}', '{}', 6),

-- ── Spirituality ────────────────────────────────────────────────────────────────
($a$Stillness is always available.$a$, 'spirituality', '{spiritual}', 2, 'beginner', '{stillness}', '{}', 4),
($a$I move with purpose.$a$, 'spirituality', '{practical}', 3, 'beginner', '{direction}', '{find-purpose}', 4),
($a$I trust the unfolding.$a$, 'spirituality', '{spiritual}', 2, 'beginner', '{faith,letting-go}', '{}', 4),
($a$I am held by something larger.$a$, 'spirituality', '{spiritual}', 2, 'intermediate', '{faith}', '{}', 6),
($a$I am part of something whole.$a$, 'spirituality', '{spiritual}', 2, 'intermediate', '{belonging,faith}', '{}', 6),
($a$I listen more than I ask.$a$, 'spirituality', '{spiritual}', 2, 'intermediate', '{stillness}', '{}', 6),
($a$Silence has its own answers.$a$, 'spirituality', '{spiritual}', 2, 'advanced', '{stillness}', '{}', 5),
($a$I surrender what I cannot understand.$a$, 'spirituality', '{spiritual}', 2, 'advanced', '{letting-go,faith}', '{}', 6),
($a$The present is sacred enough.$a$, 'spirituality', '{spiritual}', 2, 'advanced', '{presence}', '{}', 5),
($a$Faith is rest, not certainty.$a$, 'spirituality', '{spiritual}', 2, 'advanced', '{faith}', '{}', 5),
($a$I am a small part of a large thing.$a$, 'spirituality', '{spiritual}', 2, 'intermediate', '{belonging}', '{}', 9),
($a$I let mystery be enough.$a$, 'spirituality', '{spiritual}', 2, 'advanced', '{faith,letting-go}', '{}', 5),
($a$I belong to the whole of it.$a$, 'spirituality', '{spiritual}', 2, 'intermediate', '{belonging}', '{}', 7),
($a$I make peace with not knowing.$a$, 'spirituality', '{spiritual}', 2, 'advanced', '{letting-go,faith}', '{}', 6),
($a$The quiet is not empty.$a$, 'spirituality', '{spiritual}', 2, 'advanced', '{stillness}', '{}', 5),
($a$I am carried more than I carry.$a$, 'spirituality', '{spiritual}', 2, 'intermediate', '{faith}', '{}', 7),
($a$I bow to what I cannot explain.$a$, 'spirituality', '{spiritual}', 2, 'advanced', '{faith}', '{}', 7),
($a$I let the day be a prayer.$a$, 'spirituality', '{spiritual}', 2, 'intermediate', '{presence,faith}', '{}', 7),
($a$Wonder is my default.$a$, 'spirituality', '{gentle}', 2, 'beginner', '{stillness}', '{}', 4),
($a$I trust the slow design.$a$, 'spirituality', '{spiritual}', 2, 'intermediate', '{faith}', '{}', 5),
($a$I am here, which is enough.$a$, 'spirituality', '{spiritual}', 2, 'beginner', '{presence}', '{}', 6),
($a$I loosen my grip on the plan.$a$, 'spirituality', '{gentle}', 2, 'intermediate', '{letting-go}', '{}', 7),
($a$Presence is the practice.$a$, 'spirituality', '{spiritual}', 2, 'beginner', '{presence}', '{}', 4),
($a$I let go in order to hold.$a$, 'spirituality', '{spiritual}', 2, 'advanced', '{letting-go}', '{}', 7),
($a$Stillness answers in its own time.$a$, 'spirituality', '{spiritual}', 2, 'advanced', '{stillness}', '{}', 6),

-- ── Financial Confidence ────────────────────────────────────────────────────────
($a$I make calm, clear decisions.$a$, 'financial_confidence', '{practical}', 3, 'beginner', '{calm}', '{reduce-financial-stress}', 5),
($a$I face my numbers calmly.$a$, 'financial_confidence', '{practical}', 3, 'beginner', '{calm,security}', '{reduce-financial-stress}', 5),
($a$I trust myself with money.$a$, 'financial_confidence', '{practical}', 3, 'beginner', '{self-trust,agency}', '{financial-confidence}', 5),
($a$I am building, one choice at a time.$a$, 'financial_confidence', '{practical}', 3, 'intermediate', '{discipline}', '{money-habits}', 7),
($a$Enough begins with awareness.$a$, 'financial_confidence', '{spiritual}', 2, 'intermediate', '{security}', '{}', 4),
($a$I spend in line with my values.$a$, 'financial_confidence', '{practical}', 3, 'intermediate', '{agency}', '{money-habits}', 7),
($a$Small savings are quiet power.$a$, 'financial_confidence', '{practical}', 3, 'intermediate', '{discipline}', '{money-habits}', 5),
($a$I can be careful without fear.$a$, 'financial_confidence', '{practical}', 3, 'advanced', '{calm}', '{reduce-financial-stress}', 6),
($a$Security is a habit, not a number.$a$, 'financial_confidence', '{practical}', 3, 'advanced', '{security,discipline}', '{money-habits}', 7),
($a$Money follows my attention.$a$, 'financial_confidence', '{practical}', 3, 'advanced', '{agency}', '{money-habits}', 4),
($a$I look at my money without flinching.$a$, 'financial_confidence', '{practical}', 3, 'intermediate', '{calm}', '{reduce-financial-stress}', 7),
($a$I owe my future some attention.$a$, 'financial_confidence', '{practical}', 3, 'intermediate', '{discipline}', '{money-habits}', 6),
($a$Small habits beat big windfalls.$a$, 'financial_confidence', '{practical}', 3, 'advanced', '{discipline}', '{money-habits}', 5),
($a$I let money be a tool, not a verdict.$a$, 'financial_confidence', '{spiritual}', 2, 'advanced', '{self-worth}', '{financial-confidence}', 9),
($a$I can want more and have enough.$a$, 'financial_confidence', '{spiritual}', 2, 'advanced', '{security,abundance}', '{}', 7),
($a$I save before I spend.$a$, 'financial_confidence', '{practical}', 3, 'beginner', '{discipline}', '{money-habits}', 5),
($a$I make peace with my numbers.$a$, 'financial_confidence', '{gentle}', 2, 'beginner', '{calm}', '{reduce-financial-stress}', 6),
($a$Calm decisions compound too.$a$, 'financial_confidence', '{practical}', 3, 'intermediate', '{calm,discipline}', '{}', 4),
($a$I spend on what I actually value.$a$, 'financial_confidence', '{practical}', 3, 'intermediate', '{agency}', '{money-habits}', 7),
($a$I am not my bank balance.$a$, 'financial_confidence', '{gentle}', 2, 'intermediate', '{self-worth}', '{financial-confidence}', 6),
($a$I plan instead of worry.$a$, 'financial_confidence', '{practical}', 3, 'intermediate', '{calm,discipline}', '{reduce-financial-stress}', 5),
($a$Wealth begins with attention.$a$, 'financial_confidence', '{spiritual}', 2, 'advanced', '{agency}', '{}', 4),
($a$I can learn what I do not yet know.$a$, 'financial_confidence', '{gentle}', 2, 'beginner', '{growth,agency}', '{financial-confidence}', 9),
($a$I let enough be a number I choose.$a$, 'financial_confidence', '{spiritual}', 2, 'advanced', '{security}', '{}', 8),
($a$I treat money like a quiet practice.$a$, 'financial_confidence', '{practical}', 3, 'intermediate', '{discipline}', '{money-habits}', 7),

-- ── Health & Wellness ───────────────────────────────────────────────────────────
($a$My body deserves my patience.$a$, 'health_wellness', '{gentle}', 2, 'beginner', '{body}', '{}', 5),
($a$Rest is productive too.$a$, 'health_wellness', '{gentle}', 2, 'beginner', '{rest}', '{low-energy}', 4),
($a$I honor what my body needs.$a$, 'health_wellness', '{gentle}', 2, 'beginner', '{body}', '{}', 6),
($a$Energy returns with care.$a$, 'health_wellness', '{gentle}', 2, 'intermediate', '{energy,rest}', '{low-energy}', 4),
($a$I move because it feels good.$a$, 'health_wellness', '{practical}', 3, 'intermediate', '{vitality}', '{better-health}', 6),
($a$Health is built in small days.$a$, 'health_wellness', '{practical}', 3, 'intermediate', '{body}', '{better-health}', 6),
($a$I listen before I push.$a$, 'health_wellness', '{gentle}', 2, 'intermediate', '{body,rest}', '{}', 5),
($a$My body keeps honest score.$a$, 'health_wellness', '{practical}', 3, 'advanced', '{body}', '{}', 5),
($a$Gentleness is also discipline.$a$, 'health_wellness', '{spiritual}', 2, 'advanced', '{body,rest}', '{}', 4),
($a$I tend myself like something living.$a$, 'health_wellness', '{spiritual}', 2, 'advanced', '{body}', '{}', 6),
($a$I keep promises to my body.$a$, 'health_wellness', '{practical}', 3, 'intermediate', '{body,discipline}', '{better-health}', 6),
($a$Sleep is not a luxury.$a$, 'health_wellness', '{practical}', 3, 'beginner', '{rest}', '{low-energy}', 5),
($a$I move in ways I will repeat.$a$, 'health_wellness', '{practical}', 3, 'intermediate', '{vitality}', '{better-health}', 7),
($a$I eat like I respect myself.$a$, 'health_wellness', '{practical}', 3, 'intermediate', '{body}', '{better-health}', 6),
($a$My body is not a project.$a$, 'health_wellness', '{gentle}', 2, 'advanced', '{body,self-acceptance}', '{}', 6),
($a$I rest before I am wrecked.$a$, 'health_wellness', '{gentle}', 2, 'intermediate', '{rest}', '{low-energy}', 6),
($a$Strength is built on recovery.$a$, 'health_wellness', '{practical}', 3, 'advanced', '{rest,vitality}', '{}', 5),
($a$I drink the water, take the walk.$a$, 'health_wellness', '{practical}', 3, 'beginner', '{vitality}', '{better-health}', 7),
($a$I notice what my body asks.$a$, 'health_wellness', '{gentle}', 2, 'intermediate', '{body}', '{}', 6),
($a$Health is the long game.$a$, 'health_wellness', '{practical}', 3, 'beginner', '{body}', '{better-health}', 5),
($a$I am not punishing my body into health.$a$, 'health_wellness', '{practical}', 3, 'advanced', '{body,self-compassion}', '{}', 8),
($a$A gentle pace still arrives.$a$, 'health_wellness', '{gentle}', 2, 'intermediate', '{vitality}', '{}', 5),
($a$I let good days be normal.$a$, 'health_wellness', '{gentle}', 2, 'intermediate', '{vitality}', '{}', 6),
($a$My body is on my team.$a$, 'health_wellness', '{gentle}', 2, 'beginner', '{body}', '{}', 6),
($a$I tend the basics first.$a$, 'health_wellness', '{practical}', 3, 'beginner', '{body,rest}', '{}', 5),

-- ── Creativity ──────────────────────────────────────────────────────────────────
($a$I create before I judge.$a$, 'creativity', '{practical}', 3, 'beginner', '{curiosity}', '{}', 5),
($a$Curiosity leads the way.$a$, 'creativity', '{gentle}', 2, 'beginner', '{curiosity}', '{}', 4),
($a$The first draft is allowed to be bad.$a$, 'creativity', '{gentle}', 2, 'beginner', '{growth}', '{fear-of-failure}', 8),
($a$My ideas deserve room to breathe.$a$, 'creativity', '{gentle}', 2, 'intermediate', '{curiosity}', '{}', 6),
($a$Imperfect and made is enough.$a$, 'creativity', '{practical}', 3, 'intermediate', '{growth}', '{}', 5),
($a$I follow the interesting thread.$a$, 'creativity', '{practical}', 3, 'intermediate', '{curiosity}', '{}', 5),
($a$I make without asking permission.$a$, 'creativity', '{motivational}', 4, 'intermediate', '{agency,curiosity}', '{}', 5),
($a$Play is serious work.$a$, 'creativity', '{spiritual}', 2, 'advanced', '{curiosity}', '{}', 4),
($a$Originality is honest attention.$a$, 'creativity', '{spiritual}', 2, 'advanced', '{curiosity,presence}', '{}', 4),
($a$I trust what wants to come through.$a$, 'creativity', '{spiritual}', 2, 'advanced', '{curiosity}', '{}', 7),
($a$I make bad things on the way to good.$a$, 'creativity', '{practical}', 3, 'intermediate', '{growth}', '{fear-of-failure}', 10),
($a$I keep my hands moving.$a$, 'creativity', '{practical}', 3, 'beginner', '{action}', '{procrastination}', 5),
($a$Ideas come to those who start.$a$, 'creativity', '{practical}', 3, 'intermediate', '{action,curiosity}', '{procrastination}', 6),
($a$I borrow widely and make it mine.$a$, 'creativity', '{practical}', 3, 'advanced', '{curiosity}', '{}', 7),
($a$I protect the fragile early draft.$a$, 'creativity', '{gentle}', 2, 'advanced', '{growth}', '{}', 6),
($a$I make for myself first.$a$, 'creativity', '{practical}', 3, 'intermediate', '{agency}', '{}', 5),
($a$A narrow door makes me clever.$a$, 'creativity', '{spiritual}', 2, 'advanced', '{curiosity}', '{}', 6),
($a$I follow delight, not the algorithm.$a$, 'creativity', '{practical}', 3, 'advanced', '{curiosity}', '{}', 6),
($a$I let the work surprise me.$a$, 'creativity', '{gentle}', 2, 'intermediate', '{curiosity}', '{}', 6),
($a$I show up; the muse negotiates.$a$, 'creativity', '{humorous}', 3, 'advanced', '{curiosity}', '{}', 6),
($a$I value finished over flawless.$a$, 'creativity', '{practical}', 3, 'intermediate', '{growth}', '{fear-of-failure}', 5),
($a$I keep a door open for accidents.$a$, 'creativity', '{spiritual}', 2, 'advanced', '{curiosity}', '{}', 7),
($a$I make small things often.$a$, 'creativity', '{practical}', 3, 'beginner', '{action,mastery}', '{}', 5),
($a$I trust the next sentence to come.$a$, 'creativity', '{gentle}', 2, 'intermediate', '{curiosity,faith}', '{}', 7),
($a$I create to find out what I think.$a$, 'creativity', '{spiritual}', 2, 'advanced', '{curiosity}', '{}', 8),

-- ── Purpose & Meaning ───────────────────────────────────────────────────────────
($a$I move toward what matters.$a$, 'purpose_meaning', '{practical}', 3, 'beginner', '{direction,meaning}', '{find-purpose}', 5),
($a$My direction is mine to choose.$a$, 'purpose_meaning', '{practical}', 3, 'beginner', '{direction,agency}', '{find-purpose}', 6),
($a$I follow what feels true.$a$, 'purpose_meaning', '{gentle}', 2, 'beginner', '{meaning}', '{find-purpose}', 5),
($a$Meaning is built, not found.$a$, 'purpose_meaning', '{spiritual}', 2, 'intermediate', '{meaning}', '{find-purpose}', 5),
($a$My values point the way.$a$, 'purpose_meaning', '{practical}', 3, 'intermediate', '{direction}', '{find-purpose}', 5),
($a$I do what only I can do.$a$, 'purpose_meaning', '{practical}', 3, 'intermediate', '{meaning}', '{}', 7),
($a$I choose direction over speed.$a$, 'purpose_meaning', '{practical}', 3, 'intermediate', '{direction}', '{}', 5),
($a$Purpose hides in small acts.$a$, 'purpose_meaning', '{spiritual}', 2, 'advanced', '{meaning}', '{find-purpose}', 5),
($a$I would rather be useful than certain.$a$, 'purpose_meaning', '{spiritual}', 2, 'advanced', '{meaning}', '{}', 7),
($a$A small life can be a full one.$a$, 'purpose_meaning', '{spiritual}', 2, 'advanced', '{meaning}', '{}', 8),
($a$I trade applause for alignment.$a$, 'purpose_meaning', '{practical}', 3, 'advanced', '{direction}', '{comparison}', 5),
($a$I do small things with care.$a$, 'purpose_meaning', '{gentle}', 2, 'beginner', '{meaning,presence}', '{}', 6),
($a$Meaning is a practice, not a prize.$a$, 'purpose_meaning', '{spiritual}', 2, 'advanced', '{meaning}', '{}', 7),
($a$I follow what I cannot stop thinking about.$a$, 'purpose_meaning', '{practical}', 3, 'intermediate', '{direction,curiosity}', '{find-purpose}', 8),
($a$I would rather matter than impress.$a$, 'purpose_meaning', '{practical}', 3, 'intermediate', '{meaning}', '{comparison}', 6),
($a$I build a life I do not escape from.$a$, 'purpose_meaning', '{spiritual}', 2, 'advanced', '{meaning,direction}', '{}', 9),
($a$Purpose is the next right thing.$a$, 'purpose_meaning', '{practical}', 3, 'intermediate', '{direction}', '{find-purpose}', 6),
($a$I let my work be of use.$a$, 'purpose_meaning', '{gentle}', 2, 'beginner', '{meaning}', '{}', 7),
($a$I am pointed somewhere true.$a$, 'purpose_meaning', '{spiritual}', 2, 'intermediate', '{direction}', '{find-purpose}', 5),
($a$I spend my days on what lasts.$a$, 'purpose_meaning', '{practical}', 3, 'intermediate', '{meaning,direction}', '{}', 7),
($a$A clear why carries any how.$a$, 'purpose_meaning', '{spiritual}', 2, 'advanced', '{meaning}', '{}', 6),
($a$I do what is mine to do.$a$, 'purpose_meaning', '{practical}', 3, 'beginner', '{meaning}', '{}', 7),
($a$I measure a life in meaning.$a$, 'purpose_meaning', '{spiritual}', 2, 'intermediate', '{meaning}', '{}', 6),
($a$I let purpose be quiet.$a$, 'purpose_meaning', '{gentle}', 2, 'beginner', '{meaning}', '{}', 5),
($a$I choose depth over noise.$a$, 'purpose_meaning', '{practical}', 3, 'intermediate', '{direction,focus}', '{}', 5),

-- ── Resilience ──────────────────────────────────────────────────────────────────
($a$I outlast my hard days.$a$, 'resilience', '{practical}', 3, 'beginner', '{courage}', '{grief-loss}', 5),
($a$I bend without breaking.$a$, 'resilience', '{practical}', 3, 'beginner', '{courage}', '{}', 4),
($a$I begin again, gently.$a$, 'resilience', '{gentle}', 2, 'beginner', '{healing}', '{}', 4),
($a$Hard seasons end.$a$, 'resilience', '{gentle}', 2, 'beginner', '{impermanence}', '{grief-loss}', 3),
($a$I get back up differently.$a$, 'resilience', '{practical}', 3, 'intermediate', '{growth,courage}', '{fear-of-failure}', 5),
($a$I am still here, and that counts.$a$, 'resilience', '{gentle}', 2, 'intermediate', '{self-worth}', '{grief-loss}', 7),
($a$I recover at my own pace.$a$, 'resilience', '{gentle}', 2, 'intermediate', '{healing}', '{}', 6),
($a$Strength is also softness.$a$, 'resilience', '{spiritual}', 2, 'advanced', '{courage,self-compassion}', '{}', 4),
($a$I carry what I have learned, not just the weight.$a$, 'resilience', '{spiritual}', 2, 'advanced', '{growth,healing}', '{grief-loss}', 10),
($a$Endurance is quiet courage.$a$, 'resilience', '{spiritual}', 2, 'advanced', '{courage}', '{}', 4),
($a$I metabolize what I cannot change.$a$, 'resilience', '{spiritual}', 2, 'advanced', '{letting-go,healing}', '{grief-loss}', 6),
($a$I am practiced at beginning.$a$, 'resilience', '{practical}', 3, 'intermediate', '{courage,growth}', '{}', 5),
($a$I let bad days be just days.$a$, 'resilience', '{gentle}', 2, 'beginner', '{impermanence}', '{}', 7),
($a$I keep a little hope in reserve.$a$, 'resilience', '{gentle}', 2, 'intermediate', '{healing}', '{grief-loss}', 7),
($a$I am not back to normal; I am forward.$a$, 'resilience', '{practical}', 3, 'advanced', '{growth}', '{grief-loss}', 9),
($a$I rebuild with what remains.$a$, 'resilience', '{practical}', 3, 'intermediate', '{healing}', '{grief-loss}', 5),
($a$Breaking taught me where I bend.$a$, 'resilience', '{spiritual}', 2, 'advanced', '{growth}', '{}', 6),
($a$I am still becoming, not undone.$a$, 'resilience', '{gentle}', 2, 'intermediate', '{growth,self-worth}', '{}', 6),
($a$I rest as part of recovering.$a$, 'resilience', '{gentle}', 2, 'intermediate', '{rest,healing}', '{low-energy}', 6),
($a$I have outlived worse stories.$a$, 'resilience', '{practical}', 3, 'intermediate', '{courage}', '{grief-loss}', 5),
($a$I let grief and grit share a seat.$a$, 'resilience', '{spiritual}', 2, 'advanced', '{grief,courage}', '{grief-loss}', 8),
($a$I return to myself slowly.$a$, 'resilience', '{gentle}', 2, 'beginner', '{healing}', '{grief-loss}', 5),
($a$Hard does not mean impossible.$a$, 'resilience', '{practical}', 3, 'beginner', '{courage}', '{fear-of-failure}', 5),
($a$I carry forward, lighter each time.$a$, 'resilience', '{gentle}', 2, 'intermediate', '{healing,growth}', '{grief-loss}', 6),
($a$I trust myself in the wreckage.$a$, 'resilience', '{practical}', 3, 'advanced', '{self-trust,courage}', '{grief-loss}', 6),

-- ── Emotional Wellness ──────────────────────────────────────────────────────────
($a$My feelings are allowed here.$a$, 'emotional_wellness', '{gentle}', 2, 'beginner', '{self-compassion}', '{negative-self-talk}', 5),
($a$Sadness is not a failure.$a$, 'emotional_wellness', '{gentle}', 2, 'beginner', '{self-acceptance}', '{grief-loss}', 5),
($a$What I feel, I can face.$a$, 'emotional_wellness', '{practical}', 3, 'beginner', '{courage}', '{}', 6),
($a$I let it move through me.$a$, 'emotional_wellness', '{gentle}', 2, 'intermediate', '{letting-go,healing}', '{}', 6),
($a$Naming it softens it.$a$, 'emotional_wellness', '{practical}', 3, 'intermediate', '{self-compassion}', '{stress-overwhelm}', 4),
($a$I sit with what is.$a$, 'emotional_wellness', '{spiritual}', 2, 'intermediate', '{acceptance,presence}', '{}', 5),
($a$I do not have to fix this now.$a$, 'emotional_wellness', '{gentle}', 2, 'intermediate', '{acceptance,letting-go}', '{stress-overwhelm}', 8),
($a$I make space before I judge.$a$, 'emotional_wellness', '{gentle}', 2, 'intermediate', '{self-compassion}', '{negative-self-talk}', 6),
($a$Feelings are visitors, not residents.$a$, 'emotional_wellness', '{spiritual}', 2, 'advanced', '{letting-go,impermanence}', '{}', 5),
($a$I can hold two things at once.$a$, 'emotional_wellness', '{spiritual}', 2, 'advanced', '{acceptance}', '{}', 7),
($a$I feel it so it can pass.$a$, 'emotional_wellness', '{gentle}', 2, 'intermediate', '{letting-go,healing}', '{}', 7),
($a$I am not too much.$a$, 'emotional_wellness', '{gentle}', 2, 'beginner', '{self-acceptance}', '{negative-self-talk}', 5),
($a$A hard feeling is not a flaw.$a$, 'emotional_wellness', '{gentle}', 2, 'intermediate', '{self-acceptance}', '{negative-self-talk}', 7),
($a$I let the wave have its minute.$a$, 'emotional_wellness', '{gentle}', 2, 'intermediate', '{letting-go,impermanence}', '{}', 7),
($a$I put words to what I feel.$a$, 'emotional_wellness', '{practical}', 3, 'beginner', '{self-compassion}', '{}', 7),
($a$I do not rush my own grief.$a$, 'emotional_wellness', '{gentle}', 2, 'intermediate', '{grief,healing}', '{grief-loss}', 7),
($a$Numb is a feeling too.$a$, 'emotional_wellness', '{practical}', 3, 'advanced', '{acceptance}', '{}', 5),
($a$I let myself be soft today.$a$, 'emotional_wellness', '{gentle}', 2, 'beginner', '{self-compassion}', '{}', 6),
($a$I make peace with mixed feelings.$a$, 'emotional_wellness', '{spiritual}', 2, 'intermediate', '{acceptance}', '{}', 6),
($a$My calm returns; it always has.$a$, 'emotional_wellness', '{gentle}', 2, 'intermediate', '{calm,impermanence}', '{stress-overwhelm}', 6),
($a$I hold the feeling, not the story.$a$, 'emotional_wellness', '{practical}', 3, 'advanced', '{letting-go,presence}', '{negative-self-talk}', 7),
($a$I let comfort in.$a$, 'emotional_wellness', '{gentle}', 2, 'beginner', '{self-compassion}', '{loneliness}', 4),
($a$I am allowed to not be okay.$a$, 'emotional_wellness', '{gentle}', 2, 'beginner', '{self-acceptance}', '{}', 7),
($a$Feelings inform; they do not command.$a$, 'emotional_wellness', '{practical}', 3, 'advanced', '{letting-go}', '{}', 6),
($a$I greet what arrives in me.$a$, 'emotional_wellness', '{spiritual}', 2, 'intermediate', '{acceptance,presence}', '{}', 6)

on conflict (category, text) do nothing;

-- ── Validation queries (run manually after seeding) ─────────────────────────────
-- select category, count(*) from affirmation_library group by category order by category;  -- expect 25 each
-- select count(*) from affirmation_library;                                                -- expect 350
-- select text, word_count from affirmation_library where word_count not between 3 and 12;  -- expect 0 rows
-- select category, difficulty, count(*) from affirmation_library group by 1,2 order by 1,2;
